---
title: "Activity 1.2 - RStudio and R Markdown"
author: "Aaron Villafuerte"
date: "8/26/2019"
output: 
  html_document: 
    fig_height: 6
    fig_width: 10
    highlight: espresso
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

datasaurus_dozen has 1846 rows and 3 columns, the three variables are dataset, x , y 

### Exercise 2

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

And next calculate the correlation between `x` and `y` in this dataset:

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```
The correlation between x and y is -0.06447185	

### Exercise 3

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()

```

```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```
The correlation between 'x' and 'y' is -0.0629611

### Exercise 4


```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r}
circle_data %>%
  summarize(r = cor(x, y))
```
The correlation between 'x' and 'y' is -0.06834336	

### Exercise 5

```{r}
ggplot(data = datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
  geom_point() +
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")

```


```{r}

datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)

```